<?php

return [
    'user_plans' => [
        'Free' => [
            'name' => 'Free',
            'type' => 'Free',
            'payment_status' => 'free',
            'badge' => null,
            'price' => 0,
            'duration_value' => 3650,
            'duration_unit' => 'days',
            'features' => [
                'display' => [
                    'Basic search',
                    'Limited chats',
                    'No Boost',
                ],
                'basic_search' => true,
                'unlimited_chats' => false,
                'chat_limit' => 3,
                'boosts_per_month' => 0,
                'super_likes_per_day' => 0,
                'vip_badge' => false,
                'vvip_badge' => false,
                'see_who_liked' => false,
            ],
        ],
        'VIP' => [
            'name' => 'VIP Plan',
            'type' => 'VIP',
            'payment_status' => 'paid',
            'badge' => 'VIP',
            'price' => 2499,
            'duration_value' => 1,
            'duration_unit' => 'months',
            'features' => [
                'display' => [
                    'Unlimited chats',
                    '5 Boosts per Month',
                    '5 Super Likes per Day',
                    'VIP Badge',
                ],
                'basic_search' => true,
                'unlimited_chats' => true,
                'chat_limit' => null,
                'boosts_per_month' => 5,
                'super_likes_per_day' => 5,
                'vip_badge' => true,
                'vvip_badge' => false,
                'see_who_liked' => true,
            ],
        ],
        'VVIP' => [
            'name' => 'VVIP Plan',
            'type' => 'VVIP',
            'payment_status' => 'paid',
            'badge' => 'VVIP',
            'price' => 3999,
            'duration_value' => 1,
            'duration_unit' => 'months',
            'features' => [
                'display' => [
                    'Everything in VIP Plan',
                    'Unlimited chats',
                    'Unlimited Super likes',
                    'Unlimited Boosts per Month',
                    'VVIP Badge',
                ],
                'basic_search' => true,
                'unlimited_chats' => true,
                'chat_limit' => null,
                'boosts_per_month' => null,
                'super_likes_per_day' => null,
                'vip_badge' => true,
                'vvip_badge' => true,
                'see_who_liked' => true,
            ],
        ],
    ],

    'mb_plan' => [
        'name' => 'Marriage Bureau Plan',
        'type' => 'MB',
        'payment_status' => 'paid',
        'price' => 5000,
        'duration_value' => 1,
        'duration_unit' => 'months',
        'features' => [
            'Full app access',
            'All features unlocked',
            'Unlimited users management',
            'Complete marriage bureau panel access',
        ],
    ],
];
